In [10]:
import pandas as pd

names = range(0, 19)

transit = pd.read_csv('/kaggle/input/new-york-city-transport-statistics/mta_1706.csv', header=None, names=names, low_memory=False)

# Display the first few rows of the DataFrame
transit.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,RecordedAtTime,DirectionRef,PublishedLineName,OriginName,OriginLat,OriginLong,DestinationName,DestinationLat,DestinationLong,VehicleRef,VehicleLocation.Latitude,VehicleLocation.Longitude,NextStopPointName,ArrivalProximityText,DistanceFromStop,ExpectedArrivalTime,ScheduledArrivalTime,NaN,NaN
1,2017-06-01 00:03:34,0,B8,4 AV/95 ST,40.616104,-74.031143,BROWNSVILLE ROCKAWAY AV,40.656048,-73.907379,NYCT_430,40.63517,-73.960803,FOSTER AV/E 18 ST,approaching,76,2017-06-01 00:03:59,24:06:14,NaN,NaN
2,2017-06-01 00:03:43,1,S61,ST GEORGE FERRY/S61 & S91,40.643169,-74.073494,S I MALL YUKON AV,40.575935,-74.167686,NYCT_8263,40.590802,-74.15834,MERRYMOUNT ST/TRAVIS AV,approaching,62,2017-06-01 00:03:56,23:58:02,NaN,NaN
3,2017-06-01 00:03:49,0,Bx10,E 206 ST/BAINBRIDGE AV,40.875008,-73.880142,RIVERDALE 263 ST,40.912376,-73.902534,NYCT_4223,40.88601,-73.912647,HENRY HUDSON PKY E/W 235 ST,at stop,5,2017-06-01 00:03:56,24:00:53,NaN,NaN
4,2017-06-01 00:03:31,0,Q5,TEARDROP/LAYOVER,40.701748,-73.802399,ROSEDALE LIRR STA via MERRICK,40.666012,-73.735939,NYCT_8422,40.668002,-73.729348,HOOK CREEK BL/SUNRISE HY,< 1 stop away,267,2017-06-01 00:04:03,24:03:00,NaN,NaN

In [11]:
transit.tail()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
6730852,2017-06-30 23:53:37,0,B54,JAY ST/MYRTLE PLZ,40.694504,-73.987122,RIDGEWOOD TERM via MYRTLE,40.700527,-73.910149,NYCT_4442,40.699765,-73.911974,GATES AV/WYCKOFF AV,approaching,47,2017-06-30 23:53:52,23:44:12,NaN,NaN
6730853,2017-06-30 23:53:13,1,M79-SBS,E 79 ST/EAST END AV,40.770741,-73.948715,SELECT BUS W SIDE RIVERSIDE DR CROSSTOWN,40.784988,-73.98246,NYCT_5927,40.770681,-73.948759,E 79 ST/EAST END AV,at stop,0,NaN,24:02:00,NaN,NaN
6730854,2017-06-30 23:53:21,1,M5,BROADWAY/W 178 ST,40.848522,-73.937706,31 ST 6 AV,40.747791,-73.988831,NYCT_6388,40.82042,-73.955842,W 135 ST/RIVERSIDE DR,approaching,120,2017-06-30 23:54:27,23:44:16,NaN,NaN
6730855,2017-06-30 23:53:34,0,M4,W 32 ST/7 AV,40.749405,-73.99102,WASH HTS CABRINI BLV via MADSON via BWAY,40.859013,-73.93425,NYCT_6392,40.797009,-73.948954,CENTRAL PK N/5 AV,at stop,22,2017-06-30 23:53:42,23:50:00,NaN,NaN
6730856,2017-06-30 23:53:18,0,Bx2,LINCOLN AV/E 137 ST,40.809616,-73.928276,KNGSBRDG HTS FT INDEP ST via CONCOURSE,40.878746,-73.898033,NYCT_4750,40.817354,-73.922631,E 149 ST/MORRIS AV,approaching,37,2017-06-30 23:53:39,23:45:15,NaN,NaN

In [12]:
#drop the null column 18 (column 18 is fully null)
transit.drop(columns=18, inplace=True)
transit

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,RecordedAtTime,DirectionRef,PublishedLineName,OriginName,OriginLat,OriginLong,DestinationName,DestinationLat,DestinationLong,VehicleRef,VehicleLocation.Latitude,VehicleLocation.Longitude,NextStopPointName,ArrivalProximityText,DistanceFromStop,ExpectedArrivalTime,ScheduledArrivalTime,NaN
1,2017-06-01 00:03:34,0,B8,4 AV/95 ST,40.616104,-74.031143,BROWNSVILLE ROCKAWAY AV,40.656048,-73.907379,NYCT_430,40.63517,-73.960803,FOSTER AV/E 18 ST,approaching,76,2017-06-01 00:03:59,24:06:14,NaN
2,2017-06-01 00:03:43,1,S61,ST GEORGE FERRY/S61 & S91,40.643169,-74.073494,S I MALL YUKON AV,40.575935,-74.167686,NYCT_8263,40.590802,-74.15834,MERRYMOUNT ST/TRAVIS AV,approaching,62,2017-06-01 00:03:56,23:58:02,NaN
3,2017-06-01 00:03:49,0,Bx10,E 206 ST/BAINBRIDGE AV,40.875008,-73.880142,RIVERDALE 263 ST,40.912376,-73.902534,NYCT_4223,40.88601,-73.912647,HENRY HUDSON PKY E/W 235 ST,at stop,5,2017-06-01 00:03:56,24:00:53,NaN
4,2017-06-01 00:03:31,0,Q5,TEARDROP/LAYOVER,40.701748,-73.802399,ROSEDALE LIRR STA via MERRICK,40.666012,-73.735939,NYCT_8422,40.668002,-73.729348,HOOK CREEK BL/SUNRISE HY,< 1 stop away,267,2017-06-01 00:04:03,24:03:00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6730852,2017-06-30 23:53:37,0,B54,JAY ST/MYRTLE PLZ,40.694504,-73.987122,RIDGEWOOD TERM via MYRTLE,40.700527,-73.910149,NYCT_4442,40.699765,-73.911974,GATES AV/WYCKOFF AV,approaching,47,2017-06-30 23:53:52,23:44:12,NaN
6730853,2017-06-30 23:53:13,1,M79-SBS,E 79 ST/EAST END AV,40.770741,-73.948715,SELECT BUS W SIDE RIVERSIDE DR CROSSTOWN,40.784988,-73.98246,NYCT_5927,40.770681,-73.948759,E 79 ST/EAST END AV,at stop,0,NaN,24:02:00,NaN
6730854,2017-06-30 23:53:21,1,M5,BROADWAY/W 178 ST,40.848522,-73.937706,31 ST 6 AV,40.747791,-73.988831,NYCT_6388,40.82042,-73.955842,W 135 ST/RIVERSIDE DR,approaching,120,2017-06-30 23:54:27,23:44:16,NaN
6730855,2017-06-30 23:53:34,0,M4,W 32 ST/7 AV,40.749405,-73.99102,WASH HTS CABRINI BLV via MADSON via BWAY,40.859013,-73.93425,NYCT_6392,40.797009,-73.948954,CENTRAL PK N/5 AV,at stop,22,2017-06-30 23:53:42,23:50:00,NaN
6730856,2017-06-30 23:53:18,0,Bx2,LINCOLN AV/E 137 ST,40.809616,-73.928276,KNGSBRDG HTS FT INDEP ST via CONCOURSE,40.878746,-73.898033,NYCT_4750,40.817354,-73.922631,E 149 ST/MORRIS AV,approaching,37,2017-06-30 23:53:39,23:45:15,NaN

In [14]:
#Replace the index header by the original header
headers = transit.iloc[0]
#Get rid of those nulls.
headers = headers.fillna(value='unknown')
#Rename the headers.
transit = transit.rename(columns=headers)

In [15]:
problems = transit.loc[~transit['unknown'].isna()]
problems.iloc[:,-8:]
#Some rows the pandas has issue in reading.
#It seperate the NextStopPointName into 2 column(due to the comma in the description) hence some rows has column 17.

,VehicleLocation.Latitude,VehicleLocation.Longitude,NextStopPointName,ArrivalProximityText,DistanceFromStop,ExpectedArrivalTime,ScheduledArrivalTime,unknown
53191,40.800789,-73.958297,CPW/110st (non-public,for GEO),at stop,0,NaN,08:32:43
56711,40.778027,-73.981934,W 72 ST/Amsterdam av ( non-public,for GEO),approaching,86,2017-06-01 08:44:42,08:47:50
64873,40.774443,-73.982081,W 72 ST/Amsterdam av ( non-public,for GEO),< 1 stop away,485,2017-06-01 09:15:32,09:11:50
80635,40.778227,-73.981891,W 72 ST/Amsterdam av ( non-public,for GEO),approaching,64,2017-06-01 10:25:01,10:17:50
97071,40.777501,-73.981963,W 72 ST/Amsterdam av ( non-public,for GEO),approaching,145,2017-06-01 11:55:31,11:45:08
...,...,...,...,...,...,...,...,...
6602011,40.800789,-73.958297,CPW/110st (non-public,for GEO),at stop,0,NaN,13:22:43
6610541,40.776424,-73.982004,W 72 ST/Amsterdam av ( non-public,for GEO),< 1 stop away,265,2017-06-30 14:13:36,14:06:08
6637528,40.776065,-73.982019,W 72 ST/Amsterdam av ( non-public,for GEO),< 1 stop away,305,2017-06-30 16:05:23,16:06:08
6643651,40.777398,-73.981966,W 72 ST/Amsterdam av ( non-public,for GEO),< 1 stop away,156,2017-06-30 16:23:59,16:26:08
6689854,40.77686,-73.981986,W 72 ST/Amsterdam av ( non-public,for GEO),< 1 stop away,216,2017-06-30 19:14:20,19:13:08

In [16]:
#The following cells is used to fix that reading bug. By just shifting the values in error row by 1.
#Arrival Proximity.
transit["ArrivalProximityText"].loc[~transit["unknown"].isna()] = problems['DistanceFromStop']

In [17]:
#DistanceFromStop
transit["DistanceFromStop"].loc[~transit['unknown'].isna()] = problems['ExpectedArrivalTime']

In [18]:
#ExpectedArrivalTime
transit["ExpectedArrivalTime"].loc[~transit['unknown'].isna()] = problems['ScheduledArrivalTime']

In [19]:
#ScheduledArrivalTime
transit["ScheduledArrivalTime"].loc[~transit['unknown'].isna()] = problems['unknown']
#drop that unknown column
transit.drop(columns='unknown', inplace=True)

In [20]:
#A summary of missing variables represented as a percentage of the total missing content.
def missingness_summary(df, print_log=False, sort='ascending'):
  s = df.isnull().sum()*100/df.isnull().count()

  if sort.lower() == 'ascending':
    s = s.sort_values(ascending=True)
  elif sort.lower() == 'descending':
    s = s.sort_values(ascending=False)
  if print_log:
    print(s)

  return pd.Series(s)

In [21]:
missingness_summary(transit)

RecordedAtTime                0.000000
DirectionRef                  0.000000
PublishedLineName             0.000000
DestinationName               0.000000
VehicleLocation.Longitude     0.000000
VehicleLocation.Latitude      0.000000
VehicleRef                    0.000000
DistanceFromStop              0.104028
ArrivalProximityText          0.104028
NextStopPointName             0.104028
DestinationLong               0.153710
DestinationLat                0.153710
OriginLong                    0.938335
OriginLat                     0.938335
OriginName                    0.938335
ScheduledArrivalTime          2.560343
ExpectedArrivalTime          12.960430
dtype: float64

In [22]:
#Drop the duplicates, inclusive of all but the scheduled arrival time (sometimes there's more than one.)
subset = transit.columns[0:16]
transit.drop_duplicates(subset=subset, inplace=True)

Now the raw data is processed and can read without any error. The next part is to extract the features that we need for our model.

# At the Stop

Investigating situations where the buses are at the stop already. DistanceFromStop should equal zero.

Columns of interest
* RecordedAtTime
* PublishedLineName
* DestinationName
* VehicleLocation.Longitude
* VehicleLocation.Latitude
* NextStopPointName
* VehicleRef
* DistanceFromStop
* ScheduledArrivalTime

In [68]:
#get the rows and columns of interest.
coi = ['RecordedAtTime','PublishedLineName','DirectionRef','VehicleRef','DestinationLat','DestinationLong', 'NextStopPointName','OriginLat','OriginLong','VehicleLocation.Latitude', 'VehicleLocation.Longitude','DistanceFromStop','ScheduledArrivalTime']
atthestop = transit[coi].loc[transit.DistanceFromStop == '0'].copy()
atthestop.info()

<class 'pandas.core.frame.DataFrame'>
Index: 367855 entries, 7 to 6730853
Data columns (total 13 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   RecordedAtTime             367855 non-null  object
 1   PublishedLineName          367855 non-null  object
 2   DirectionRef               367855 non-null  object
 3   VehicleRef                 367855 non-null  object
 4   DestinationLat             367354 non-null  object
 5   DestinationLong            367354 non-null  object
 6   NextStopPointName          367855 non-null  object
 7   OriginLat                  364638 non-null  object
 8   OriginLong                 364638 non-null  object
 9   VehicleLocation.Latitude   367855 non-null  object
 10  VehicleLocation.Longitude  367855 non-null  object
 11  DistanceFromStop           367855 non-null  object
 12  ScheduledArrivalTime       330403 non-null  object
dtypes: object(13)
memory usage: 39.3+ MB

In [69]:
#quick look at what's going on with the scheduled arrival time, null values.
transit[(transit.ScheduledArrivalTime.isna())]

,RecordedAtTime,DirectionRef,PublishedLineName,OriginName,OriginLat,OriginLong,DestinationName,DestinationLat,DestinationLong,VehicleRef,VehicleLocation.Latitude,VehicleLocation.Longitude,NextStopPointName,ArrivalProximityText,DistanceFromStop,ExpectedArrivalTime,ScheduledArrivalTime
13,2017-06-01 00:03:35,1,B26,WYCKOFF ST/PALMETTO ST,40.69915,-73.910477,DNTWN BKLYN TILLARY ST via HALSEY,40.693939,-73.990311,NYCT_6503,40.693922,-73.990411,CADMAN PZ W/TILLARY ST,approaching,47,NaN,NaN
202,2017-06-01 00:03:30,1,M11,RIVERBANK ST PK/CULTURAL CTR,40.826702,-73.955475,WEST VILL ABINGDON SQ via 9 AV,40.737072,-74.005867,NYCT_6720,40.737063,-74.005771,BETHUNE ST/GREENWICH ST,approaching,51,NaN,NaN
269,2017-06-01 00:03:29,0,B64,STILLWELL AV/MERMAID AV,40.577091,-73.981636,BAY RIDGE SHORE RD via 13 AV via BAY RDG,40.63707,-74.036087,NYCT_7147,40.637107,-74.036189,SHORE RD/MACKAY PL,at stop,15,NaN,NaN
341,2017-06-01 00:03:30,1,Q3,165 ST/TERMINAL,40.707558,-73.795502,JFK AIRPORT via FARMERS BL,40.647137,-73.779427,NYCT_8107,40.647079,-73.779486,JFK AIRPORT/TERMINAL 5 AirTrain STATION,at stop,0,NaN,NaN
348,2017-06-01 00:03:35,1,B16,LINCOLN RD/FLATBUSH AV,40.660843,-73.961464,BAY RIDGE SHORE RD,40.611717,-74.035072,NYCT_422,40.611669,-74.035166,SHORE RD/4 AV,at stop,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6730687,2017-06-30 23:53:29,1,M60-SBS,LGA/TERMINAL D,40.768387,-73.862534,WEST SIDE BWAY - 106 ST,40.801422,-73.968239,NYCT_5843,40.801484,-73.9682,BROADWAY/W 106 ST,at stop,0,NaN,NaN
6730773,2017-06-30 23:53:28,1,M116,PLEASANT AV/E 120 ST,40.797245,-73.931694,WEST SIDE BWAY - 106 ST XTOWN,40.801331,-73.967598,NYCT_6725,40.801256,-73.967654,W 106 ST/BROADWAY,approaching,102,NaN,NaN
6730778,2017-06-30 23:53:30,0,B37,SHORE RD/4 AV,40.611763,-74.035118,ATLANTIC AV BARCLAYS CENTER via 3 AV,40.683529,-73.979073,NYCT_761,40.68351,-73.979021,4 AV/DEAN ST,at stop,0,NaN,NaN
6730823,2017-06-30 23:53:16,1,Bx13,RIVER AV/E 150 ST,40.820633,-73.929497,WASHINGTON HTS GW BRIDGE,40.849113,-73.937752,NYCT_4353,40.849073,-73.937763,W 178 ST/FT WASHINGTON AV,approaching,60,NaN,NaN
6730832,2017-06-30 23:53:33,1,Q36,256 ST/JAMAICA AV,40.727776,-73.708687,JAMAICA 165 ST TERM,40.707615,-73.79554,NYCT_6486,40.707646,-73.795448,165 ST TERM/165 ST TERM BAY 6,at stop,0,NaN,NaN

In [70]:
#I can't disern anything. There's plenty of information. Drop these.
atthestop.dropna(inplace=True)

In [71]:
#We don't need DistanceFromStop anymore
atthestop.drop(columns='DistanceFromStop', inplace=True)

In [72]:
atthestop

,RecordedAtTime,PublishedLineName,DirectionRef,VehicleRef,DestinationLat,DestinationLong,NextStopPointName,OriginLat,OriginLong,VehicleLocation.Latitude,VehicleLocation.Longitude,ScheduledArrivalTime
7,2017-06-01 00:03:24,B31,0,NYCT_4611,40.608433,-73.9571,GERRITSEN AV/GERRITSEN BEACH,40.587101,-73.918503,40.587024,-73.918623,24:08:00
48,2017-06-01 00:03:23,Bx1,1,NYCT_5685,40.809654,-73.92836,RIVERDALE AV/W 231 ST,40.881187,-73.90934,40.881224,-73.90939,24:19:00
52,2017-06-01 00:03:30,Bx39,0,NYCT_4718,40.903309,-73.849922,WHITE PLAINS RD/LAFAYETTE AV,40.807869,-73.852715,40.822127,-73.858291,24:00:10
53,2017-06-01 00:03:49,Q44-SBS,1,NYCT_5999,40.704933,-73.79332,MAIN ST/UNION TP,40.84256,-73.878334,40.717817,-73.817285,23:59:49
87,2017-06-01 00:03:24,X10,1,NYCT_2660,40.633698,-74.129776,E 57 ST/LEXINGTON AV,40.760429,-73.967674,40.761108,-73.969562,23:51:05
...,...,...,...,...,...,...,...,...,...,...,...,...
6730721,2017-06-30 23:53:32,Bx19,0,NYCT_5943,40.861202,-73.880676,E 149 ST/COURTLANDT AV,40.826702,-73.955475,40.816609,-73.919758,23:51:28
6730775,2017-06-30 23:53:19,B46,1,NYCT_4573,40.609142,-73.92144,MALCOLM X BL/MADISON ST,40.709393,-73.959518,40.686797,-73.929827,23:46:12
6730783,2017-06-30 23:53:31,B15,0,NYCT_6826,40.646908,-73.779564,DUMONT AV/FOUNTAIN AV,40.699722,-73.941513,40.66931,-73.873951,23:12:17
6730846,2017-06-30 23:53:31,M100,1,NYCT_4401,40.802273,-73.931145,DYCKMAN ST/NAGLE AV,40.871967,-73.91304,40.861808,-73.924881,23:47:40
6730853,2017-06-30 23:53:13,M79-SBS,1,NYCT_5927,40.784988,-73.98246,E 79 ST/EAST END AV,40.770741,-73.948715,40.770681,-73.948759,24:02:00

In [73]:
atthestop[(transit.ScheduledArrivalTime.isna())]

/tmp/ipykernel_42/4010497482.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  atthestop[(transit.ScheduledArrivalTime.isna())]

Empty DataFrame
Columns: [RecordedAtTime, PublishedLineName, DirectionRef, VehicleRef, DestinationLat, DestinationLong, NextStopPointName, OriginLat, OriginLong, VehicleLocation.Latitude, VehicleLocation.Longitude, ScheduledArrivalTime]
Index: []

In [74]:
#Convert the lat and long to numeric.
atthestop['VehicleLat'] = atthestop['VehicleLocation.Latitude'].apply(pd.to_numeric, errors='coerce')
atthestop['VehicleLong'] = atthestop['VehicleLocation.Longitude'].apply(pd.to_numeric, errors='coerce')
atthestop.drop(columns=['VehicleLocation.Latitude', 'VehicleLocation.Longitude'], inplace=True)
atthestop

,RecordedAtTime,PublishedLineName,DirectionRef,VehicleRef,DestinationLat,DestinationLong,NextStopPointName,OriginLat,OriginLong,ScheduledArrivalTime,VehicleLat,VehicleLong
7,2017-06-01 00:03:24,B31,0,NYCT_4611,40.608433,-73.9571,GERRITSEN AV/GERRITSEN BEACH,40.587101,-73.918503,24:08:00,40.587024,-73.918623
48,2017-06-01 00:03:23,Bx1,1,NYCT_5685,40.809654,-73.92836,RIVERDALE AV/W 231 ST,40.881187,-73.90934,24:19:00,40.881224,-73.909390
52,2017-06-01 00:03:30,Bx39,0,NYCT_4718,40.903309,-73.849922,WHITE PLAINS RD/LAFAYETTE AV,40.807869,-73.852715,24:00:10,40.822127,-73.858291
53,2017-06-01 00:03:49,Q44-SBS,1,NYCT_5999,40.704933,-73.79332,MAIN ST/UNION TP,40.84256,-73.878334,23:59:49,40.717817,-73.817285
87,2017-06-01 00:03:24,X10,1,NYCT_2660,40.633698,-74.129776,E 57 ST/LEXINGTON AV,40.760429,-73.967674,23:51:05,40.761108,-73.969562
...,...,...,...,...,...,...,...,...,...,...,...,...
6730721,2017-06-30 23:53:32,Bx19,0,NYCT_5943,40.861202,-73.880676,E 149 ST/COURTLANDT AV,40.826702,-73.955475,23:51:28,40.816609,-73.919758
6730775,2017-06-30 23:53:19,B46,1,NYCT_4573,40.609142,-73.92144,MALCOLM X BL/MADISON ST,40.709393,-73.959518,23:46:12,40.686797,-73.929827
6730783,2017-06-30 23:53:31,B15,0,NYCT_6826,40.646908,-73.779564,DUMONT AV/FOUNTAIN AV,40.699722,-73.941513,23:12:17,40.669310,-73.873951
6730846,2017-06-30 23:53:31,M100,1,NYCT_4401,40.802273,-73.931145,DYCKMAN ST/NAGLE AV,40.871967,-73.91304,23:47:40,40.861808,-73.924881
6730853,2017-06-30 23:53:13,M79-SBS,1,NYCT_5927,40.784988,-73.98246,E 79 ST/EAST END AV,40.770741,-73.948715,24:02:00,40.770681,-73.948759

In [75]:
#Recorded at time converted to date time.
atthestop['RecordedAtTime'] = pd.to_datetime(atthestop['RecordedAtTime'], errors = 'coerce')
tindex = pd.DatetimeIndex(atthestop.RecordedAtTime)
#Recorded Year, Day, and Month as a separate column for convenience
atthestop['RecordDate'] = tindex.strftime('%Y-%m-%d ')

In [76]:
#Troubleshooting scheduled arrival time.
sTimes = atthestop[['ScheduledArrivalTime', 'RecordDate']].loc[atthestop.ScheduledArrivalTime >= "24"]

In [77]:
#year-month-day as string
ymd = sTimes.RecordDate
hours = sTimes.ScheduledArrivalTime.str[0:2]
rest = sTimes.ScheduledArrivalTime.str[2:]
# subtract 24
hours = hours.astype(int) - 24
# reassign the string
converted = hours.astype(str) + rest
converted = ymd + converted
# make it datetime, adding one to the day because it's after midnight.
converted = pd.to_datetime(converted, format = '%Y-%m-%d %H:%M:%S')
converted = converted

In [78]:
from datetime import datetime, timedelta
#scheduled column as Scheduled arrival time converted to date time.
atthestop['scheduled'] = pd.to_datetime(atthestop['RecordDate'] + atthestop['ScheduledArrivalTime'], format = '%Y-%m-%d %H:%M:%S', errors='coerce')
atthestop['scheduled'].fillna(value=converted, inplace=True)

#correct for situations after midnight.
condition = (atthestop.scheduled - atthestop.RecordedAtTime).astype('timedelta64[s]') >= timedelta(minutes=1000)
atthestop.loc[condition, ['scheduled']] = atthestop.loc[condition, ['scheduled']] - timedelta(days=1)

condition = (atthestop.scheduled - atthestop.RecordedAtTime).astype('timedelta64[s]') <= timedelta(minutes=-1000)
atthestop.loc[condition, ['scheduled']] = atthestop.loc[condition, ['scheduled']] + timedelta(days=1)

#late indicator
condition = (atthestop.scheduled - atthestop.RecordedAtTime).astype('timedelta64[s]') < timedelta(minutes=0)
atthestop['late'] = condition

#adherence
atthestop['adherence'] = (atthestop.scheduled - atthestop.RecordedAtTime).astype('timedelta64[s]') / pd.Timedelta(minutes=1)
atthestop['adherence'] = atthestop['adherence'].astype('int')

#Calculate the day of the week
atthestop['day_of_week']= atthestop['scheduled'].dt.strftime("%A")

In [79]:
atthestop

,RecordedAtTime,PublishedLineName,DirectionRef,VehicleRef,DestinationLat,DestinationLong,NextStopPointName,OriginLat,OriginLong,ScheduledArrivalTime,VehicleLat,VehicleLong,RecordDate,scheduled,late,adherence,day_of_week
7,2017-06-01 00:03:24,B31,0,NYCT_4611,40.608433,-73.9571,GERRITSEN AV/GERRITSEN BEACH,40.587101,-73.918503,24:08:00,40.587024,-73.918623,2017-06-01,2017-06-01 00:08:00,False,4,Thursday
48,2017-06-01 00:03:23,Bx1,1,NYCT_5685,40.809654,-73.92836,RIVERDALE AV/W 231 ST,40.881187,-73.90934,24:19:00,40.881224,-73.909390,2017-06-01,2017-06-01 00:19:00,False,15,Thursday
52,2017-06-01 00:03:30,Bx39,0,NYCT_4718,40.903309,-73.849922,WHITE PLAINS RD/LAFAYETTE AV,40.807869,-73.852715,24:00:10,40.822127,-73.858291,2017-06-01,2017-06-01 00:00:10,True,-3,Thursday
53,2017-06-01 00:03:49,Q44-SBS,1,NYCT_5999,40.704933,-73.79332,MAIN ST/UNION TP,40.84256,-73.878334,23:59:49,40.717817,-73.817285,2017-06-01,2017-05-31 23:59:49,True,-4,Wednesday
87,2017-06-01 00:03:24,X10,1,NYCT_2660,40.633698,-74.129776,E 57 ST/LEXINGTON AV,40.760429,-73.967674,23:51:05,40.761108,-73.969562,2017-06-01,2017-05-31 23:51:05,True,-12,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6730721,2017-06-30 23:53:32,Bx19,0,NYCT_5943,40.861202,-73.880676,E 149 ST/COURTLANDT AV,40.826702,-73.955475,23:51:28,40.816609,-73.919758,2017-06-30,2017-06-30 23:51:28,True,-2,Friday
6730775,2017-06-30 23:53:19,B46,1,NYCT_4573,40.609142,-73.92144,MALCOLM X BL/MADISON ST,40.709393,-73.959518,23:46:12,40.686797,-73.929827,2017-06-30,2017-06-30 23:46:12,True,-7,Friday
6730783,2017-06-30 23:53:31,B15,0,NYCT_6826,40.646908,-73.779564,DUMONT AV/FOUNTAIN AV,40.699722,-73.941513,23:12:17,40.669310,-73.873951,2017-06-30,2017-06-30 23:12:17,True,-41,Friday
6730846,2017-06-30 23:53:31,M100,1,NYCT_4401,40.802273,-73.931145,DYCKMAN ST/NAGLE AV,40.871967,-73.91304,23:47:40,40.861808,-73.924881,2017-06-30,2017-06-30 23:47:40,True,-5,Friday
6730853,2017-06-30 23:53:13,M79-SBS,1,NYCT_5927,40.784988,-73.98246,E 79 ST/EAST END AV,40.770741,-73.948715,24:02:00,40.770681,-73.948759,2017-06-30,2017-07-01 00:02:00,False,8,Saturday

In [80]:
atthestop.drop(columns='ScheduledArrivalTime', inplace=True)

In [81]:
atthestop.drop(columns='RecordDate', inplace=True)
atthestop

,RecordedAtTime,PublishedLineName,DirectionRef,VehicleRef,DestinationLat,DestinationLong,NextStopPointName,OriginLat,OriginLong,VehicleLat,VehicleLong,scheduled,late,adherence,day_of_week
7,2017-06-01 00:03:24,B31,0,NYCT_4611,40.608433,-73.9571,GERRITSEN AV/GERRITSEN BEACH,40.587101,-73.918503,40.587024,-73.918623,2017-06-01 00:08:00,False,4,Thursday
48,2017-06-01 00:03:23,Bx1,1,NYCT_5685,40.809654,-73.92836,RIVERDALE AV/W 231 ST,40.881187,-73.90934,40.881224,-73.909390,2017-06-01 00:19:00,False,15,Thursday
52,2017-06-01 00:03:30,Bx39,0,NYCT_4718,40.903309,-73.849922,WHITE PLAINS RD/LAFAYETTE AV,40.807869,-73.852715,40.822127,-73.858291,2017-06-01 00:00:10,True,-3,Thursday
53,2017-06-01 00:03:49,Q44-SBS,1,NYCT_5999,40.704933,-73.79332,MAIN ST/UNION TP,40.84256,-73.878334,40.717817,-73.817285,2017-05-31 23:59:49,True,-4,Wednesday
87,2017-06-01 00:03:24,X10,1,NYCT_2660,40.633698,-74.129776,E 57 ST/LEXINGTON AV,40.760429,-73.967674,40.761108,-73.969562,2017-05-31 23:51:05,True,-12,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6730721,2017-06-30 23:53:32,Bx19,0,NYCT_5943,40.861202,-73.880676,E 149 ST/COURTLANDT AV,40.826702,-73.955475,40.816609,-73.919758,2017-06-30 23:51:28,True,-2,Friday
6730775,2017-06-30 23:53:19,B46,1,NYCT_4573,40.609142,-73.92144,MALCOLM X BL/MADISON ST,40.709393,-73.959518,40.686797,-73.929827,2017-06-30 23:46:12,True,-7,Friday
6730783,2017-06-30 23:53:31,B15,0,NYCT_6826,40.646908,-73.779564,DUMONT AV/FOUNTAIN AV,40.699722,-73.941513,40.669310,-73.873951,2017-06-30 23:12:17,True,-41,Friday
6730846,2017-06-30 23:53:31,M100,1,NYCT_4401,40.802273,-73.931145,DYCKMAN ST/NAGLE AV,40.871967,-73.91304,40.861808,-73.924881,2017-06-30 23:47:40,True,-5,Friday
6730853,2017-06-30 23:53:13,M79-SBS,1,NYCT_5927,40.784988,-73.98246,E 79 ST/EAST END AV,40.770741,-73.948715,40.770681,-73.948759,2017-07-01 00:02:00,False,8,Saturday

In [85]:
weather = pd.read_csv('/kaggle/input/nyc-weather/New-York-CityUSA-2017-06-01-to-2017-06-30.csv', low_memory=False)

# Display the first few rows of the DataFrame
weather.head()

,name,datetime,temp,feelslike,dew,humidity,precip,precipprob,preciptype,snow,...,sealevelpressure,cloudcover,visibility,solarradiation,solarenergy,uvindex,severerisk,conditions,icon,stations
0,"New York City,USA",2017-06-01T00:00:00,20.4,20.4,16.2,76.80,0.0,0,NaN,0,...,1014.2,5.1,15.6,0.0,0.0,0,NaN,Clear,clear-night,"72505394728,72055399999,KLGA,KNYC,72503014732"
1,"New York City,USA",2017-06-01T01:00:00,18.2,18.2,14.9,80.88,0.0,0,NaN,0,...,1014.6,3.6,16.0,0.0,0.0,0,NaN,Clear,clear-night,"72505394728,72055399999,KLGA,KNYC,72503014732"
2,"New York City,USA",2017-06-01T02:00:00,17.7,17.7,13.3,75.28,0.0,0,NaN,0,...,1014.2,0.8,16.0,0.0,0.0,0,NaN,Clear,clear-night,"72505394728,72055399999,KLGA,KNYC,72503014732"
3,"New York City,USA",2017-06-01T03:00:00,17.0,17.0,13.8,81.41,0.0,0,NaN,0,...,1014.8,1.9,16.0,0.0,0.0,0,NaN,Clear,clear-night,"72505394728,72055399999,KLGA,KNYC,72503014732"
4,"New York City,USA",2017-06-01T04:00:00,17.0,17.0,13.9,81.83,0.0,0,NaN,0,...,1014.2,51.9,16.0,0.0,0.0,0,NaN,Partially cloudy,partly-cloudy-night,"72505394728,72055399999,KLGA,KNYC,72503014732"

In [86]:
weather['datetime'] = pd.to_datetime(weather['datetime'])
weather

,name,datetime,temp,feelslike,dew,humidity,precip,precipprob,preciptype,snow,...,sealevelpressure,cloudcover,visibility,solarradiation,solarenergy,uvindex,severerisk,conditions,icon,stations
0,"New York City,USA",2017-06-01 00:00:00,20.4,20.4,16.2,76.80,0.0,0,NaN,0,...,1014.2,5.1,15.6,0.0,0.0,0,NaN,Clear,clear-night,"72505394728,72055399999,KLGA,KNYC,72503014732"
1,"New York City,USA",2017-06-01 01:00:00,18.2,18.2,14.9,80.88,0.0,0,NaN,0,...,1014.6,3.6,16.0,0.0,0.0,0,NaN,Clear,clear-night,"72505394728,72055399999,KLGA,KNYC,72503014732"
2,"New York City,USA",2017-06-01 02:00:00,17.7,17.7,13.3,75.28,0.0,0,NaN,0,...,1014.2,0.8,16.0,0.0,0.0,0,NaN,Clear,clear-night,"72505394728,72055399999,KLGA,KNYC,72503014732"
3,"New York City,USA",2017-06-01 03:00:00,17.0,17.0,13.8,81.41,0.0,0,NaN,0,...,1014.8,1.9,16.0,0.0,0.0,0,NaN,Clear,clear-night,"72505394728,72055399999,KLGA,KNYC,72503014732"
4,"New York City,USA",2017-06-01 04:00:00,17.0,17.0,13.9,81.83,0.0,0,NaN,0,...,1014.2,51.9,16.0,0.0,0.0,0,NaN,Partially cloudy,partly-cloudy-night,"72505394728,72055399999,KLGA,KNYC,72503014732"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
715,"New York City,USA",2017-06-30 19:00:00,28.9,31.0,20.7,61.33,0.0,0,NaN,0,...,1013.1,4.3,16.0,91.6,0.3,1,NaN,Clear,clear-day,"72505394728,72055399999,KLGA,KNYC,72503014732"
716,"New York City,USA",2017-06-30 20:00:00,28.4,30.4,20.7,62.93,0.0,0,NaN,0,...,1013.8,6.8,16.0,3.2,0.0,0,NaN,Clear,clear-day,"72505394728,72055399999,KLGA,KNYC,72503014732"
717,"New York City,USA",2017-06-30 21:00:00,27.9,30.1,21.1,66.59,0.0,0,NaN,0,...,1014.5,30.4,16.0,0.0,0.0,0,NaN,Partially cloudy,partly-cloudy-night,"72505394728,72055399999,KLGA,KNYC,72503014732"
718,"New York City,USA",2017-06-30 22:00:00,27.2,29.0,20.7,67.36,0.0,0,NaN,0,...,1015.5,28.3,16.0,0.0,0.0,0,NaN,Partially cloudy,partly-cloudy-night,"72505394728,72055399999,KLGA,KNYC,72503014732"
719,"New York City,USA",2017-06-30 23:00:00,26.8,28.4,20.6,68.92,0.0,0,NaN,0,...,1015.1,62.7,16.0,0.0,0.0,0,NaN,Partially cloudy,partly-cloudy-night,"72505394728,72055399999,KLGA,KNYC,72503014732"

In [93]:
#Augment the vehicle data with weather information at that hour
def add_weather_data(data):
    for index, row in data.iterrows():
        wrow = weather.iloc[(weather['datetime'] - row['RecordedAtTime']).abs().argsort()[:1]]
        data.at[index,'Temp'] = list(wrow['temp'])[0]
        data.at[index,'Pressure'] = list(wrow['sealevelpressure'])[0]
        data.at[index,'Humidity'] = list(wrow['humidity'])[0]
        data.at[index,'WindSpeed'] = list(wrow['windspeed'])[0]
        data.at[index,'Clouds'] = list(wrow['cloudcover'])[0]
        data.at[index,'Visibility'] = list(wrow['visibility'])[0]
        data.at[index,'WeatherConditions'] = list(wrow['conditions'])[0]
    return(data)

In [94]:
#See that I didn't mess up
test_aug = add_weather_data(atthestop.tail())
test_aug

/tmp/ipykernel_42/2339575873.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.at[index,'Temp'] = list(wrow['temp'])[0]
/tmp/ipykernel_42/2339575873.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.at[index,'Pressure'] = list(wrow['sealevelpressure'])[0]
/tmp/ipykernel_42/2339575873.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.at[index,'Humidity'] = list(wrow['humidity'])[0]
/tmp/ipykernel_42/2339575873.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.at[index,'WindSpeed'] = list(wrow['windspeed'])[0]
/tmp/ipykernel_42/2339575873.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.at[index,'Clouds'] = list(wrow['cloudcover'])[0]
/tmp/ipykernel_42/2339575873.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.at[index,'Visibility'] = list(wrow['visibility'])[0]
/tmp/ipykernel_42/2339575873.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.at[index,'WeatherConditions'] = list(wrow['conditions'])[0]

,RecordedAtTime,PublishedLineName,DirectionRef,VehicleRef,DestinationLat,DestinationLong,NextStopPointName,OriginLat,OriginLong,VehicleLat,...,late,adherence,day_of_week,Temp,Pressure,Humidity,WindSpeed,Clouds,Visibility,WeatherConditions
6730721,2017-06-30 23:53:32,Bx19,0,NYCT_5943,40.861202,-73.880676,E 149 ST/COURTLANDT AV,40.826702,-73.955475,40.816609,...,True,-2,Friday,26.8,1015.1,68.92,16.1,62.7,16.0,Partially cloudy
6730775,2017-06-30 23:53:19,B46,1,NYCT_4573,40.609142,-73.92144,MALCOLM X BL/MADISON ST,40.709393,-73.959518,40.686797,...,True,-7,Friday,26.8,1015.1,68.92,16.1,62.7,16.0,Partially cloudy
6730783,2017-06-30 23:53:31,B15,0,NYCT_6826,40.646908,-73.779564,DUMONT AV/FOUNTAIN AV,40.699722,-73.941513,40.669310,...,True,-41,Friday,26.8,1015.1,68.92,16.1,62.7,16.0,Partially cloudy
6730846,2017-06-30 23:53:31,M100,1,NYCT_4401,40.802273,-73.931145,DYCKMAN ST/NAGLE AV,40.871967,-73.91304,40.861808,...,True,-5,Friday,26.8,1015.1,68.92,16.1,62.7,16.0,Partially cloudy
6730853,2017-06-30 23:53:13,M79-SBS,1,NYCT_5927,40.784988,-73.98246,E 79 ST/EAST END AV,40.770741,-73.948715,40.770681,...,False,8,Saturday,26.8,1015.1,68.92,16.1,62.7,16.0,Partially cloudy

In [95]:
#Ok, seems right
data = add_weather_data(atthestop)
data

,RecordedAtTime,PublishedLineName,DirectionRef,VehicleRef,DestinationLat,DestinationLong,NextStopPointName,OriginLat,OriginLong,VehicleLat,...,late,adherence,day_of_week,Temp,Pressure,Humidity,WindSpeed,Clouds,Visibility,WeatherConditions
7,2017-06-01 00:03:24,B31,0,NYCT_4611,40.608433,-73.9571,GERRITSEN AV/GERRITSEN BEACH,40.587101,-73.918503,40.587024,...,False,4,Thursday,20.4,1014.2,76.80,20.8,5.1,15.6,Clear
48,2017-06-01 00:03:23,Bx1,1,NYCT_5685,40.809654,-73.92836,RIVERDALE AV/W 231 ST,40.881187,-73.90934,40.881224,...,False,15,Thursday,20.4,1014.2,76.80,20.8,5.1,15.6,Clear
52,2017-06-01 00:03:30,Bx39,0,NYCT_4718,40.903309,-73.849922,WHITE PLAINS RD/LAFAYETTE AV,40.807869,-73.852715,40.822127,...,True,-3,Thursday,20.4,1014.2,76.80,20.8,5.1,15.6,Clear
53,2017-06-01 00:03:49,Q44-SBS,1,NYCT_5999,40.704933,-73.79332,MAIN ST/UNION TP,40.84256,-73.878334,40.717817,...,True,-4,Wednesday,20.4,1014.2,76.80,20.8,5.1,15.6,Clear
87,2017-06-01 00:03:24,X10,1,NYCT_2660,40.633698,-74.129776,E 57 ST/LEXINGTON AV,40.760429,-73.967674,40.761108,...,True,-12,Wednesday,20.4,1014.2,76.80,20.8,5.1,15.6,Clear
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6730721,2017-06-30 23:53:32,Bx19,0,NYCT_5943,40.861202,-73.880676,E 149 ST/COURTLANDT AV,40.826702,-73.955475,40.816609,...,True,-2,Friday,26.8,1015.1,68.92,16.1,62.7,16.0,Partially cloudy
6730775,2017-06-30 23:53:19,B46,1,NYCT_4573,40.609142,-73.92144,MALCOLM X BL/MADISON ST,40.709393,-73.959518,40.686797,...,True,-7,Friday,26.8,1015.1,68.92,16.1,62.7,16.0,Partially cloudy
6730783,2017-06-30 23:53:31,B15,0,NYCT_6826,40.646908,-73.779564,DUMONT AV/FOUNTAIN AV,40.699722,-73.941513,40.669310,...,True,-41,Friday,26.8,1015.1,68.92,16.1,62.7,16.0,Partially cloudy
6730846,2017-06-30 23:53:31,M100,1,NYCT_4401,40.802273,-73.931145,DYCKMAN ST/NAGLE AV,40.871967,-73.91304,40.861808,...,True,-5,Friday,26.8,1015.1,68.92,16.1,62.7,16.0,Partially cloudy
6730853,2017-06-30 23:53:13,M79-SBS,1,NYCT_5927,40.784988,-73.98246,E 79 ST/EAST END AV,40.770741,-73.948715,40.770681,...,False,8,Saturday,26.8,1015.1,68.92,16.1,62.7,16.0,Partially cloudy

In [ ]:
data['RecordedAtTime'] = pd.to_datetime(data['RecordedAtTime']).dt.time

In [96]:
#Exporting 
data.to_csv('processed_data.csv', index=False)